### ISSUE TITLE
when use as log4j appender, when fluentd is dead application also died

### ISSUE THREAD

**Issue by tantra35** [fluent/fluent-logger-node#31]
Minimal example to reproduce

```
var log4js=require("log4js");

log4js.addAppender(require('fluent-logger').support.log4jsAppender('app.test', {
   host: '/tmp/fluentd.sock',
   timeout: 3.0
}));

var logger = log4js.getLogger('foo');

 setInterval(function() {
  latency = Math.round(Math.random() * 100);
  logger.info('this log record is sent to fluent daemon');
}, 5000);
```

when we stop fluentd we got follow error, and application stop

```
user@social:~/test/log# node ./test.js
[2015-09-18 18:42:31.166] [INFO] foo - this log record is sent to fluent daemon
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED /tmp/fluentd.sock
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

**Comment by edsiper** [comment]
Looks like the problem is with Unix domain sockets, if you try the TCP connection does it works ?

**Comment by tantra35** [comment]
No this is a complex problem, due follow code (sender.js:108):

```
  var self = this;
  if( self._socket === null ){
    self._socket = new net.Socket();
    self._socket.setTimeout(self.timeout);
    self._socket.on('error', function(err){
      if( self._socket ){
        self._socket.destroy();
        self._socket = null;
//        callback(err);
        self._eventEmitter.emit('error', err); //if socket error happens this call print stack trace and kill node
      }
    });
```

So as expected when we use tcp connection we got the same error:

```
root@social:/home/ruslan/test/log# node ./test.js
[2015-09-23 18:11:14.888] [INFO] foo - this log record is sent to fluent daemon
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:24224
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

**Comment by okkez** [comment]
Application does not crash when we use plain FluentSender.
We should fix log4js.js in this library.

```js
var logger = require('fluent-logger').createFluentSender('tag', {
  host: 'localhost',
  port: 5170,
  timeout: 3.0
});

setInterval(function() {
  latency = Math.round(Math.random() * 100);
  console.log('.');
  logger.emit('label', { message: 'this log record is sent to fluent daemon' });
}, 1000);
```

**Comment by okkez** [comment]
@tantra35 @ashutalewar
test script does not crash on my environment. Please try #42
