### ISSUE TITLE
self._socket.write TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by zoell** [fluent/fluent-logger-node#48]
I am trying to build a winston transport with fluent-logger but for some reasons I receive this error:

```
TypeError: Cannot read property 'write' of null
  at FluentSender._flushSendQueue (/project/node_modules/winston-fluentd/node_modules/fluent-logger/lib/sender.js:145:17)
  at /project/node_modules/winston-fluentd/node_modules/fluent-logger/lib/sender.js:48:10
  at Socket. (/project/node_modules/winston-fluentd/node_modules/fluent-logger/lib/sender.js:118:9)
  at Socket.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:10)
```

Currently I am trying to use it in a Sails.js application.
node: 4.4.0

Here is my module code where I call fluent-logger:
```
  var logger = require('fluent-logger')
  logger.configure(this.tag, {
    host: this.host,
    port: this.port,
    timeout: 3.0,
    reconnectInterval: 600000 // 10 minutes
  });
  logger.emit(this.label, {message: msg});
```

Any idea what is causing the issue? What can I try?

**Comment by okkez** [comment]
What is `this` in your configuration?
I could not reproduce your situation.

I tested following code.
As you know this is plain configuration without winston.

```js
var config = {
  host: "localhost",
  port: 24224,
  tag: "tag",
  label: "label"
};
var msg = "This is a test message";

var logger = require('fluent-logger');
logger.configure(config.tag, {
  host: config.host,
  port: config.port,
  timeout: 3.0,
  reconnectInterval: 600000 // 10 minutes
});
logger.emit(config.label, {message: msg});
```

fluent.conf:

```aconf
<source>
  @type forward
  port 24224
</source>

<match *.**>
  @type stdout
</match>
```

**Comment by okkez** [comment]
no response
