### ISSUE TITLE
'ack in response and chunk id in sent data are different' if logs are submitted too quickly

### ISSUE THREAD

**Issue by slang800** [fluent/fluent-logger-node#67]
Using this test code:

```js
var fluent = require('./lib');
var ref = '0.0.0.0:24224'.split(':'), host = ref[0], port = ref[1];
var logger = fluent.createFluentSender('tester', {
  host: host,
  port: port,
  timeout: 3.0,
  reconnectInterval: 600000,
  requireAckResponse: true
});

var logNumber = 0;

var sendMsg = function() {
  var data, time;
  time = Math.round(Date.now() / 1000);
  data = {
    logNumber: logNumber
  };
  logNumber += 1;
  return logger.emit('test', data, time);
};

setInterval(sendMsg, 10);
```

I get these errors:

```
Fluentd error { Error
    at Timeout.<anonymous> (/home/slang/proj/forks/fluent-logger-node/lib/sender.js:204:27)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  name: 'ResponseError',
  message: 'ack in response and chunk id in sent data are different',
  options: 
   { ack: 'o5zRrA/EeHL3HUoHpB0Zhg==',
     chunk: 'rBKxRgOoDOMd/ZdzdJqOuA==' } }
Fluentd will reconnect after 600 seconds
Fluentd error { Error
    at Timeout.<anonymous> (/home/slang/proj/forks/fluent-logger-node/lib/sender.js:204:27)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  name: 'ResponseError',
  message: 'ack in response and chunk id in sent data are different',
  options: 
   { ack: 'wFehfIh/mnUp87vkZqC/xw==',
     chunk: 'tgjLYMj3Mvk6vO8I9UBo0Q==' } }
Fluentd will reconnect after 600 seconds
Fluentd error { Error
    at Timeout.<anonymous> (/home/slang/proj/forks/fluent-logger-node/lib/sender.js:204:27)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  name: 'ResponseError',
  message: 'ack in response and chunk id in sent data are different',
  options: 
   { ack: 'wi2TRtMCGKnd3+qtLpERtw==',
     chunk: '73bSwxgEXO67MkIYQtCpqQ==' } }
Fluentd will reconnect after 600 seconds
Fluentd error { Error
    at Timeout.<anonymous> (/home/slang/proj/forks/fluent-logger-node/lib/sender.js:204:27)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  name: 'ResponseError',
  message: 'ack in response and chunk id in sent data are different',
  options: 
   { ack: 'b7Qm2aMz4zTLLdHYOcEc/Q==',
     chunk: 'lzvnEts0MbpuOFfFCBHesQ==' } }
```

**Comment by okkez** [comment]
@slang800 could you try #72 ?

**Comment by slang800** [comment]
The root of the problem is that you're checking for responses on a fixed interval of 100ms: https://github.com/fluent/fluent-logger-node/blob/ea1b83236ca294b4a7473de72389a8cb2c05cb74/lib/sender.js#L210. So if more than one response is received in a 100ms window, it's ignored. I'm working on a partial rewrite to fix the way this is handled.
